POST http://localhost:3333/videos
Content-Type: application/json

{
    "title" : "video1 ",
    "description" : "primeiro video",
    "duration" : 120
}



### //separa as requisições

GET http://localhost:3333/videos?search=node

###
GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/a7d9550d-a16e-491c-ab32-5f70a58ba5b3
Content-Type: application/json

{
    "title" : "video2",
    "description" : "segundo video",
    "duration" : 120
}

###

DELETE http://localhost:3333/videos/ccb0e3d5-69f3-426d-aad5-882b490561c3


