POST http://localhost:3333/videos
Content-Type: application/json

{
    "title" : "videoy ",
    "description" : "y video",
    "duration" : 2
}



### //separa as requisições

GET http://localhost:3333/videos?search=node

###
GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/2f26db3a-65be-4d50-8eb3-00f206744ab1
Content-Type: application/json

{
    "title" : "video3",
    "description" : "segundo video",
    "duration" : 30
}

###

DELETE http://localhost:3333/videos/ccb0e3d5-69f3-426d-aad5-882b490561c3


